version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest # SQL Server 2022 image
    container_name: sqlserver
    ports:
      - "1435:1433" # map lokal port 1435 -> container 1433
    environment:
      ACCEPT_EULA: "Y" # sql license acceptance
      SA_PASSWORD: "MySqlServer123!"
    volumes:
      - sqlvolume:/var/opt/mssql # saves data in volume

volumes:
  sqlvolume:
